apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-microservice-config
  namespace: ml-microservice
data:
  APP_NAME: "ml-microservice"
  APP_ENV: "production"
  DEBUG: "false"
  LOG_LEVEL: "info"
  PORT: "8001"
  WORKERS: "4"
  # RabbitMQ config (no-credentials)
  # RABBITMQ_HOST: "rabbitmq.rabbitmq-system"
  # RABBITMQ_PORT: "5672"
  # RABBITMQ_VHOST: "/"
  RABBITMQ_HOST: "rabbitmq.rabbitmq-system.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "admin"
  RABBITMQ_PASSWORD: "newpassword"
  # Prefijos de colas RabbitMQ
  USER_EVENTS_QUEUE: "user_events"
  LOAN_EVENTS_QUEUE: "loan_events"
  PAYMENT_EVENTS_QUEUE: "payment"
  # MongoDB config (no-credentials)
  MONGO_DB: "loanData"
  # Configuración específica de ML
  MODEL_DIRECTORY: "/app/models"
  MODEL_VERSION: "1.0"
  PREDICTION_THRESHOLD: "0.75"
  RETRAIN_SCHEDULE: "0 0 * * 0"  # Cada domingo a medianoche