apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ml-microservice-hpa
  namespace: ml-microservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ml-microservice
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80