apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-microservice-exports-pvc
  namespace: ml-microservice
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 2Gi
  storageClassName: hostpath   