FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV APP_MODE=api
ENV API_PORT=8001
ENV API_HOST=0.0.0.0

WORKDIR /app

# Dependencias del sistema
RUN apt-get update && \
    apt-get install -y build-essential gcc && \
    apt-get clean

# Copiar primero requirements para aprovechar caché
COPY requirements.txt /app/
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copiar código
COPY . /app/

# Script de entrada que permite ejecutar API o Consumer
RUN echo '#!/bin/bash\n\
    if [ "$APP_MODE" = "api" ]; then\n\
    echo "Iniciando en modo API..."\n\
    python -m uvicorn app.main:app --host $API_HOST --port $API_PORT\n\
    elif [ "$APP_MODE" = "consumer" ]; then\n\
    echo "Iniciando en modo Consumer..."\n\
    python -m app.events.rabbit_consumer\n\
    else\n\
    echo "Modo no reconocido: $APP_MODE"\n\
    exit 1\n\
    fi' > /app/entrypoint.sh && \
    chmod +x /app/entrypoint.sh

EXPOSE 8001

ENTRYPOINT ["/app/entrypoint.sh"]