apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-api
  namespace: credit-scoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-api
  template:
    metadata:
      labels:
        app: ml-api
    spec:
      containers:
      - name: ml-api
        image: moisodev/ml-scoring:latest  # Reemplaza con tu imagen
        ports:
        - containerPort: 8001
        env:
        - name: APP_MODE
          value: "api"
        - name: ENABLE_INITIAL_SYNC
          value: "false"
        envFrom:
        - configMapRef:
            name: ml-config
        - secretRef:
            name: ml-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        readinessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ml-api
  namespace: credit-scoring
spec:
  selector:
    app: ml-api
  ports:
  - port: 80
    targetPort: 8001
  type: LoadBalancer  # Cambia a ClusterIP si usas Ingress