apiVersion: v1
kind: Secret
metadata:
  name: ml-secrets
  namespace: credit-scoring
type: Opaque
data:
  RABBITMQ_USER: YWRtaW4=  # admin
  RABBITMQ_PASSWORD: bmV3cGFzc3dvcmQ=  # newpassword
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # postgres
  MONGO_URI: bW9uZ29kYitzcnY6Ly9tYXVyaWNpb2FsZW1hbjM1MjQ6bWF1cmlAY2x1c3RlcjEuYjJscXZ5ei5tb25nb2RiLm5ldC8=